### PR TITLE
Feature/get usage

### PR DESCRIPTION
**Pull request by jijeesh**
added a script to get resource requests and its usage

### CODE REVIEW

**Comment by eldada** [comment]
Thx for the PR @jijeesh !
I will review in the coming days.
Can you please add an entry in README.md as well?

**Comment by eldada** [comment]
I reviewed the file. Looks like a great addition.
Since you are basically adding functionality to `getResourcesCSV.sh`, can you simply add your new code to `getResourcesCSV.sh` with a parameter like `--show-usage`? 
This will allow extra capabilities to the file instead of duplicating it.

**Comment by jijeesh** [comment]
merged into getResourceCSV.sh file

**Comment by eldada** [comment]
Thx! I will test and let you know.

**Review by eldada — APPROVED** [review]

**Comment by eldada** [comment]
@jijeesh - just note that I updated the script to always get the container usage and simplify the extraction of the numbers. You can see the final result in the master branch. Thx again for the contribution!

**Comment by jijeesh** [comment]
> @jijeesh - just note that I updated the script to always get the container usage and simplify the extraction of the numbers. You can see the final result in the master branch. Thx again for the contribution!

this is awesome :)

**Pull request merged**
